"""Catalogue complet de l'atelier de tuning GT7 + GT Auto."""

from copy import deepcopy

# Rang collectionneur minimum pour acheter l'étage en boutique.
# Les pièces Ultimate ne s'achètent pas : tickets roulette 3★/4★.
TIERS = {
    "sports": {"level": 0, "label": "Sports", "label_fr": "Sports"},
    "club": {"level": 4, "label": "Club Sports", "label_fr": "Club Sports"},
    "semi": {"level": 5, "label": "Semi-Racing", "label_fr": "Semi-Racing"},
    "racing": {"level": 6, "label": "Racing", "label_fr": "Racing"},
    "extreme": {"level": 50, "label": "Extreme", "label_fr": "Extreme"},
    "ultimate": {"level": 99, "label": "Ultimate", "label_fr": "Ultimate (roulette)"},
    "gtauto": {"level": 0, "label": "GT Auto", "label_fr": "GT Auto"},
}

# Compound order used when a race forces a tyre class.
TIRE_COMPOUNDS = [
    {"id": "CH", "name_fr": "Confort Hard", "part": "tire_ch", "grip": 1, "wear": 5, "surface": "tarmac"},
    {"id": "CM", "name_fr": "Confort Medium", "part": "tire_cm", "grip": 2, "wear": 4, "surface": "tarmac"},
    {"id": "CS", "name_fr": "Confort Soft", "part": "tire_cs", "grip": 3, "wear": 3, "surface": "tarmac"},
    {"id": "SH", "name_fr": "Sports Hard", "part": "tire_sh", "grip": 4, "wear": 5, "surface": "tarmac"},
    {"id": "SM", "name_fr": "Sports Medium", "part": "tire_sm", "grip": 5, "wear": 4, "surface": "tarmac"},
    {"id": "SS", "name_fr": "Sports Soft", "part": "tire_ss", "grip": 6, "wear": 3, "surface": "tarmac"},
    {"id": "RH", "name_fr": "Racing Hard", "part": "tire_rh", "grip": 7, "wear": 5, "surface": "tarmac"},
    {"id": "RM", "name_fr": "Racing Medium", "part": "tire_rm", "grip": 8, "wear": 4, "surface": "tarmac"},
    {"id": "RS", "name_fr": "Racing Soft", "part": "tire_rs", "grip": 9, "wear": 2, "surface": "tarmac"},
    {"id": "IM", "name_fr": "Intermédiaires", "part": "tire_im", "grip": 6, "wear": 3, "surface": "damp"},
    {"id": "W", "name_fr": "Pluie (Heavy Wet)", "part": "tire_w", "grip": 5, "wear": 3, "surface": "wet"},
    {"id": "D", "name_fr": "Dirt", "part": "tire_dirt", "grip": 6, "wear": 4, "surface": "dirt"},
    {"id": "SNOW", "name_fr": "Neige", "part": "tire_snow", "grip": 5, "wear": 4, "surface": "snow"},
]

PARTS = [
    # ── Sports ──────────────────────────────────────────────────────────
    {"id": "ecu_sport", "name_fr": "Ordinateur sport", "shop": "tuning", "tier": "sports",
     "group": "moteur", "price_min": 140000, "price_max": 250000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "ecu"], "rev": "×1.03",
     "note": "Premier gain de puissance. Seul kit moteur utilisable sur une électrique."},
    {"id": "air_sport", "name_fr": "Filtre à air sport", "shop": "tuning", "tier": "sports",
     "group": "moteur", "price_min": 60000, "price_max": 150000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "intake"],
     "note": "Réponse moteur et léger gain de puissance."},
    {"id": "muffler_sport", "name_fr": "Échappement sport", "shop": "tuning", "tier": "sports",
     "group": "moteur", "price_min": 140000, "price_max": 170000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "exhaust"],
     "note": "Légèrement plus haut-régime. Change le son et le look."},
    {"id": "pads_sport", "name_fr": "Plaquettes sport", "shop": "tuning", "tier": "sports",
     "group": "freins", "price_min": 30000, "price_max": 100000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["brakes"],
     "note": "Minimum vital avant un circuit."},
    {"id": "susp_street", "name_fr": "Suspension street", "shop": "tuning", "tier": "sports",
     "group": "chassis", "price_min": 210000, "price_max": 300000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["suspension"],
     "note": "Plus ferme, caisse un peu plus basse."},
    {"id": "wr1", "name_fr": "Allègement stade 1", "shop": "tuning", "tier": "sports",
     "group": "poids", "price_min": 300000, "price_max": 430000, "permanent": True,
     "requires": [], "replaces": [], "tags": ["weight"],
     "note": "Clim, roue de secours, batterie légère. Irréversible sans carrosserie neuve."},
    {"id": "tire_ch", "name_fr": "Pneus Confort Hard", "shop": "tuning", "tier": "sports",
     "group": "pneus", "price_min": 84000, "price_max": 130000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "CH",
     "note": "Moins d'adhérence : drift, règlement Confort, ou PP à faire baisser."},
    {"id": "tire_cm", "name_fr": "Pneus Confort Medium", "shop": "tuning", "tier": "sports",
     "group": "pneus", "price_min": 98000, "price_max": 150000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "CM"},
    {"id": "tire_cs", "name_fr": "Pneus Confort Soft", "shop": "tuning", "tier": "sports",
     "group": "pneus", "price_min": 112000, "price_max": 170000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "CS"},
    {"id": "tire_sh", "name_fr": "Pneus Sports Hard", "shop": "tuning", "tier": "sports",
     "group": "pneus", "price_min": 210000, "price_max": 400000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "SH"},
    {"id": "tire_sm", "name_fr": "Pneus Sports Medium", "shop": "tuning", "tier": "sports",
     "group": "pneus", "price_min": 250000, "price_max": 450000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "SM"},
    {"id": "tire_ss", "name_fr": "Pneus Sports Soft", "shop": "tuning", "tier": "sports",
     "group": "pneus", "price_min": 300000, "price_max": 600000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "SS",
     "note": "Meilleur pneu dispo avant le rang 6. Très fort en course courte."},

    # ── Club Sports (CL 4) ──────────────────────────────────────────────
    {"id": "bore", "name_fr": "Alésage (Bore Up)", "shop": "tuning", "tier": "club",
     "group": "moteur", "price_min": 450000, "price_max": 710000, "permanent": True,
     "requires": [], "replaces": [], "tags": ["power", "displacement"],
     "note": "Augmente la cylindrée. Irréversible sans moteur neuf."},
    {"id": "cam", "name_fr": "Arbre à cames haute levée", "shop": "tuning", "tier": "club",
     "group": "moteur", "price_min": 450000, "price_max": 630000, "permanent": True,
     "requires": [], "replaces": [], "tags": ["power", "highrpm"], "rev": "+300 tr/min",
     "note": "Plus de haut-régime. Irréversible sans moteur neuf."},
    {"id": "pistons_hc", "name_fr": "Pistons haute compression", "shop": "tuning", "tier": "club",
     "group": "moteur", "price_min": 450000, "price_max": 630000, "permanent": True,
     "requires": [], "replaces": [], "tags": ["power", "na"],
     "note": "NA uniquement. Incompatible avec un kit turbo/compressseur (retiré auto)."},
    {"id": "susp_sport", "name_fr": "Suspension sport", "shop": "tuning", "tier": "club",
     "group": "chassis", "price_min": 310000, "price_max": 400000, "permanent": False,
     "requires": [], "replaces": ["susp_street"], "tags": ["suspension"]},
    {"id": "brakes_sport", "name_fr": "Système de freinage sport", "shop": "tuning", "tier": "club",
     "group": "freins", "price_min": 100000, "price_max": 700000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["brakes"],
     "note": "Disques Brembo. Gros palier après les plaquettes."},
    {"id": "clutch_sport", "name_fr": "Embrayage & volant sport", "shop": "tuning", "tier": "club",
     "group": "transmission", "price_min": 310000, "price_max": 480000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["response"],
     "note": "Réponse moteur et frein moteur, gain d'accélération faible."},
    {"id": "lsd_1way", "name_fr": "LSD 1-way", "shop": "tuning", "tier": "club",
     "group": "transmission", "price_min": 310000, "price_max": 370000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["lsd"],
     "note": "Traction en sortie de courbe seulement."},
    {"id": "lsd_2way", "name_fr": "LSD 2-way", "shop": "tuning", "tier": "club",
     "group": "transmission", "price_min": 310000, "price_max": 370000, "permanent": False,
     "requires": [], "replaces": ["lsd_1way"], "tags": ["lsd"],
     "note": "Accélération + freinage. Plus stable à l'attaque, base drift."},
    {"id": "trans_low", "name_fr": "Boîte close-ratio courte", "shop": "tuning", "tier": "club",
     "group": "transmission", "price_min": 400000, "price_max": 650000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["gearing", "accel"],
     "note": "Accélération, Vmax en baisse. Circuits lents / techniques."},
    {"id": "trans_high", "name_fr": "Boîte close-ratio longue", "shop": "tuning", "tier": "club",
     "group": "transmission", "price_min": 480000, "price_max": 850000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["gearing", "vmax"],
     "note": "Vmax, accélération en baisse. Circuits rapides."},
    {"id": "wr2", "name_fr": "Allègement stade 2", "shop": "tuning", "tier": "club",
     "group": "poids", "price_min": 500000, "price_max": 700000, "permanent": True,
     "requires": ["wr1"], "replaces": [], "tags": ["weight"],
     "note": "Intérieur, insonorisant. Exige le stade 1."},
    {"id": "restrictor", "name_fr": "Bridle de puissance", "shop": "tuning", "tier": "club",
     "group": "pp", "price_min": 80000, "price_max": 80000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["pp", "detune"],
     "note": "Coupe le pic sans trop casser le bas/milieu. Idéal limite PP / endurance."},
    {"id": "ballast", "name_fr": "Lest (ballast)", "shop": "tuning", "tier": "club",
     "group": "pp", "price_min": 50000, "price_max": 50000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["pp", "balance"],
     "note": "Masse + position avant/arrière. Pour PP, poids mini, ou équilibre."},
    {"id": "tire_dirt", "name_fr": "Pneus Dirt", "shop": "tuning", "tier": "club",
     "group": "pneus", "price_min": 315000, "price_max": 500000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "D",
     "note": "Obligatoires en rallye terre. Pas d'élargissement via jantes/kit large."},

    # ── Semi-Racing (CL 5) ──────────────────────────────────────────────
    {"id": "crank", "name_fr": "Vilebrequin racing", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 1000000, "price_max": 1560000, "permanent": True,
     "requires": [], "replaces": [], "tags": ["power", "highrpm"], "rev": "×1.03",
     "note": "Moins de pertes haut-régime. Irréversible sans moteur neuf."},
    {"id": "ecu_full", "name_fr": "Ordinateur full custom", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 350000, "price_max": 630000, "permanent": False,
     "requires": [], "replaces": ["ecu_sport"], "tags": ["power", "ecu", "pp"],
     "rev": "×1.03",
     "note": "Puissance + réglage du % de puissance (meilleur que le bridle pour garder la courbe)."},
    {"id": "muffler_semi", "name_fr": "Échappement semi-racing", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 525000, "price_max": 800000, "permanent": False,
     "requires": [], "replaces": ["muffler_sport"], "tags": ["power", "exhaust"]},
    {"id": "turbo_low", "name_fr": "Turbo bas-régime", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 970000, "price_max": 1130000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "boost", "lowrpm"],
     "note": "Couple tôt, idéal technique. Sur NA petit cube : lag plus marqué."},
    {"id": "turbo_mid", "name_fr": "Turbo mi-régime", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 1150000, "price_max": 1350000, "permanent": False,
     "requires": [], "replaces": ["turbo_low"], "tags": ["power", "boost"],
     "note": "Le plus polyvalent. Bon upgrade d'un turbo d'origine."},
    {"id": "turbo_high", "name_fr": "Turbo haut-régime", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 1720000, "price_max": 1880000, "permanent": False,
     "requires": [], "replaces": ["turbo_mid", "turbo_low"], "tags": ["power", "boost", "highrpm"],
     "note": "Pic élevé. Peut devenir brutal sur un petit NA."},
    {"id": "sc_low", "name_fr": "Compresseur bas-régime", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 1900000, "price_max": 2100000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "boost", "lowrpm"],
     "note": "Couple immédiat, pas de lag. Plus cher qu'un turbo."},
    {"id": "ic_sport", "name_fr": "Intercooler sport", "shop": "tuning", "tier": "semi",
     "group": "moteur", "price_min": 220000, "price_max": 420000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "boost"],
     "note": "Quasi obligatoire dès qu'on pose un turbo/compressseur sur un NA."},
    {"id": "susp_sport_adj", "name_fr": "Suspension sport réglable", "shop": "tuning", "tier": "semi",
     "group": "chassis", "price_min": 520000, "price_max": 820000, "permanent": False,
     "requires": [], "replaces": ["susp_sport", "susp_street"], "tags": ["suspension"],
     "note": "Hauteur + quelques réglages. Palier avant la full custom."},
    {"id": "clutch_semi", "name_fr": "Embrayage & volant semi-racing", "shop": "tuning", "tier": "semi",
     "group": "transmission", "price_min": 520000, "price_max": 820000, "permanent": False,
     "requires": [], "replaces": ["clutch_sport"], "tags": ["response"]},
    {"id": "lsd_full", "name_fr": "LSD full custom", "shop": "tuning", "tier": "semi",
     "group": "transmission", "price_min": 400000, "price_max": 620000, "permanent": False,
     "requires": [], "replaces": ["lsd_2way", "lsd_1way"], "tags": ["lsd"],
     "note": "Init / accel / decel réglables. Pièce clé du setup."},
    {"id": "trans_manual", "name_fr": "Boîte manuelle full custom", "shop": "tuning", "tier": "semi",
     "group": "transmission", "price_min": 800000, "price_max": 1350000, "permanent": False,
     "requires": [], "replaces": ["trans_low", "trans_high"], "tags": ["gearing"],
     "note": "Rapports + pont. Indispensable dès que la puissance explose."},
    {"id": "wr3", "name_fr": "Allègement stade 3", "shop": "tuning", "tier": "semi",
     "group": "poids", "price_min": 720000, "price_max": 1050000, "permanent": True,
     "requires": ["wr2"], "replaces": [], "tags": ["weight"]},
    {"id": "rigidity", "name_fr": "Renfort de caisse", "shop": "tuning", "tier": "semi",
     "group": "chassis", "price_min": 420000, "price_max": 720000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["chassis"],
     "note": "La caisse encaisse mieux ; la voiture répond plus net."},

    # ── Racing (CL 6) ───────────────────────────────────────────────────
    {"id": "stroke", "name_fr": "Course piston (Stroke Up)", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 1400000, "price_max": 2180000, "permanent": True,
     "requires": [], "replaces": [], "tags": ["power", "displacement"],
     "note": "Cylindrée via la course. Irréversible sans moteur neuf."},
    {"id": "balance", "name_fr": "Équilibrage moteur", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 1750000, "price_max": 2680000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "highrpm"], "rev": "×1.05",
     "note": "Gros palier de régime maxi."},
    {"id": "ports", "name_fr": "Polissage des conduits", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 1200000, "price_max": 2100000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "highrpm"]},
    {"id": "als", "name_fr": "Anti-lag", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 180000, "price_max": 380000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["boost", "response"],
     "note": "Garde le turbo en pression à la décélération. Turbo uniquement."},
    {"id": "sc_high", "name_fr": "Compresseur haut-régime", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 2200000, "price_max": 2600000, "permanent": False,
     "requires": [], "replaces": ["sc_low"], "tags": ["power", "boost", "highrpm"]},
    {"id": "ic_racing", "name_fr": "Intercooler racing", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 380000, "price_max": 720000, "permanent": False,
     "requires": [], "replaces": ["ic_sport"], "tags": ["power", "boost"]},
    {"id": "air_racing", "name_fr": "Filtre à air racing", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 150000, "price_max": 320000, "permanent": False,
     "requires": [], "replaces": ["air_sport"], "tags": ["power", "intake"]},
    {"id": "muffler_racing", "name_fr": "Échappement racing", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 800000, "price_max": 1250000, "permanent": False,
     "requires": [], "replaces": ["muffler_semi", "muffler_sport"], "tags": ["power", "exhaust"]},
    {"id": "manifold", "name_fr": "Collecteur d'échappement racing", "shop": "tuning", "tier": "racing",
     "group": "moteur", "price_min": 520000, "price_max": 940000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "exhaust"]},
    {"id": "pads_racing", "name_fr": "Plaquettes racing", "shop": "tuning", "tier": "racing",
     "group": "freins", "price_min": 80000, "price_max": 220000, "permanent": False,
     "requires": [], "replaces": ["pads_sport"], "tags": ["brakes"]},
    {"id": "brakes_slot", "name_fr": "Freins racing (disques rainurés)", "shop": "tuning", "tier": "racing",
     "group": "freins", "price_min": 400000, "price_max": 1200000, "permanent": False,
     "requires": [], "replaces": ["brakes_sport"], "tags": ["brakes"]},
    {"id": "brakes_drill", "name_fr": "Freins racing (disques percés)", "shop": "tuning", "tier": "racing",
     "group": "freins", "price_min": 400000, "price_max": 1200000, "permanent": False,
     "requires": [], "replaces": ["brakes_sport"], "tags": ["brakes"],
     "note": "Même perf que les rainurés. Choix cosmétique."},
    {"id": "brake_bal", "name_fr": "Répartiteur de freinage", "shop": "tuning", "tier": "racing",
     "group": "freins", "price_min": 80000, "price_max": 160000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["brakes", "setup"],
     "note": "Réglable, y compris en course via le MFD."},
    {"id": "susp_full", "name_fr": "Suspension full custom", "shop": "tuning", "tier": "racing",
     "group": "chassis", "price_min": 1200000, "price_max": 2400000, "permanent": False,
     "requires": [], "replaces": ["susp_sport_adj", "susp_sport", "susp_street"], "tags": ["suspension"],
     "note": "Tous les réglages : hauteur, ressorts, ARB, amortisseurs, géométrie."},
    {"id": "clutch_racing", "name_fr": "Embrayage & volant racing", "shop": "tuning", "tier": "racing",
     "group": "transmission", "price_min": 720000, "price_max": 1250000, "permanent": False,
     "requires": [], "replaces": ["clutch_semi", "clutch_sport"], "tags": ["response"]},
    {"id": "center_diff", "name_fr": "Différentiel central à répartition", "shop": "tuning", "tier": "racing",
     "group": "transmission", "price_min": 520000, "price_max": 880000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["awd"], "drivetrain": ["4WD"],
     "note": "Répartition avant/arrière. 4WD uniquement."},
    {"id": "active_lsd", "name_fr": "Contrôleur LSD actif", "shop": "tuning", "tier": "racing",
     "group": "transmission", "price_min": 380000, "price_max": 720000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["lsd"],
     "note": "LSD piloté. Utile surtout en 4WD / GT."},
    {"id": "trans_seq", "name_fr": "Boîte séquentielle full custom", "shop": "tuning", "tier": "racing",
     "group": "transmission", "price_min": 1200000, "price_max": 2100000, "permanent": False,
     "requires": [], "replaces": ["trans_manual", "trans_low", "trans_high"], "tags": ["gearing"],
     "note": "Shifts ultra courts + rapports libres. Le must circuit."},
    {"id": "wr4", "name_fr": "Allègement stade 4", "shop": "tuning", "tier": "racing",
     "group": "poids", "price_min": 980000, "price_max": 1550000, "permanent": True,
     "requires": ["wr3"], "replaces": [], "tags": ["weight"]},
    {"id": "tire_rh", "name_fr": "Pneus Racing Hard", "shop": "tuning", "tier": "racing",
     "group": "pneus", "price_min": 400000, "price_max": 720000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "RH"},
    {"id": "tire_rm", "name_fr": "Pneus Racing Medium", "shop": "tuning", "tier": "racing",
     "group": "pneus", "price_min": 500000, "price_max": 850000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "RM"},
    {"id": "tire_rs", "name_fr": "Pneus Racing Soft", "shop": "tuning", "tier": "racing",
     "group": "pneus", "price_min": 600000, "price_max": 1050000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "RS",
     "note": "Meilleure adhérence asphalte sec. Usure rapide."},

    # ── Extreme (CL 50) ─────────────────────────────────────────────────
    {"id": "nitro", "name_fr": "Kit nitro", "shop": "tuning", "tier": "extreme",
     "group": "moteur", "price_min": 480000, "price_max": 980000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["power", "burst"],
     "note": "Boost ponctuel. PP en hausse, peu utile en course régulée."},
    {"id": "brakes_carbon", "name_fr": "Freins carbone-céramique", "shop": "tuning", "tier": "extreme",
     "group": "freins", "price_min": 1100000, "price_max": 2200000, "permanent": False,
     "requires": [], "replaces": ["brakes_slot", "brakes_drill", "brakes_sport"], "tags": ["brakes"],
     "note": "Même perf que les kits racing. Cosmétique / flex."},
    {"id": "handbrake", "name_fr": "Frein à main hydraulique", "shop": "tuning", "tier": "extreme",
     "group": "chassis", "price_min": 120000, "price_max": 220000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["drift", "rally"]},
    {"id": "steering_angle", "name_fr": "Adaptateur d'angle de braquage", "shop": "tuning", "tier": "extreme",
     "group": "chassis", "price_min": 80000, "price_max": 160000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["drift"]},
    {"id": "4ws", "name_fr": "Contrôleur 4WS", "shop": "tuning", "tier": "extreme",
     "group": "chassis", "price_min": 280000, "price_max": 620000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["setup"],
     "note": "Quatre roues directrices si le châssis le permet."},
    {"id": "tire_snow", "name_fr": "Pneus neige", "shop": "tuning", "tier": "extreme",
     "group": "pneus", "price_min": 300000, "price_max": 520000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "SNOW"},
    {"id": "tire_im", "name_fr": "Pneus intermédiaires", "shop": "tuning", "tier": "extreme",
     "group": "pneus", "price_min": 420000, "price_max": 720000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "IM"},
    {"id": "tire_w", "name_fr": "Pneus pluie", "shop": "tuning", "tier": "extreme",
     "group": "pneus", "price_min": 420000, "price_max": 720000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires"], "compound": "W"},
    {"id": "new_engine", "name_fr": "Moteur neuf", "shop": "tuning", "tier": "extreme",
     "group": "reset", "price_min": 500000, "price_max": 2500000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["reset"],
     "note": "Remet les mods moteur permanents à zéro (pas un swap)."},
    {"id": "new_body", "name_fr": "Carrosserie neuve", "shop": "tuning", "tier": "extreme",
     "group": "reset", "price_min": 400000, "price_max": 2200000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["reset"],
     "note": "Annule les allègements."},

    # ── Ultimate (roulette 3★/4★) ───────────────────────────────────────
    {"id": "bore_s", "name_fr": "Alésage S", "shop": "roulette", "tier": "ultimate",
     "group": "moteur", "price_min": 0, "price_max": 0, "permanent": True,
     "requires": [], "replaces": ["bore"], "tags": ["power", "ultimate"],
     "note": "Version ultime du bore up. Tickets roulette."},
    {"id": "stroke_s", "name_fr": "Course piston S", "shop": "roulette", "tier": "ultimate",
     "group": "moteur", "price_min": 0, "price_max": 0, "permanent": True,
     "requires": [], "replaces": ["stroke"], "tags": ["power", "ultimate"]},
    {"id": "ti_rods", "name_fr": "Bielles / pistons titane", "shop": "roulette", "tier": "ultimate",
     "group": "moteur", "price_min": 0, "price_max": 0, "permanent": True,
     "requires": [], "replaces": [], "tags": ["power", "ultimate", "highrpm"]},
    {"id": "cam_s", "name_fr": "Arbre à cames haute levée S", "shop": "roulette", "tier": "ultimate",
     "group": "moteur", "price_min": 0, "price_max": 0, "permanent": True,
     "requires": [], "replaces": ["cam"], "tags": ["power", "ultimate", "highrpm"]},
    {"id": "wr5", "name_fr": "Allègement stade 5", "shop": "roulette", "tier": "ultimate",
     "group": "poids", "price_min": 0, "price_max": 0, "permanent": True,
     "requires": ["wr4"], "replaces": [], "tags": ["weight", "ultimate"]},
    {"id": "carbon_shaft", "name_fr": "Arbre de transmission carbone", "shop": "roulette", "tier": "ultimate",
     "group": "transmission", "price_min": 0, "price_max": 0, "permanent": False,
     "requires": [], "replaces": [], "tags": ["response", "ultimate"]},
    {"id": "sc_high_s", "name_fr": "Compresseur haut-régime S", "shop": "roulette", "tier": "ultimate",
     "group": "moteur", "price_min": 0, "price_max": 0, "permanent": False,
     "requires": [], "replaces": ["sc_high", "sc_low"], "tags": ["power", "boost", "ultimate"]},
    {"id": "turbo_uhigh", "name_fr": "Turbo ultra haut-régime", "shop": "roulette", "tier": "ultimate",
     "group": "moteur", "price_min": 0, "price_max": 0, "permanent": False,
     "requires": [], "replaces": ["turbo_high", "turbo_mid", "turbo_low"],
     "tags": ["power", "boost", "ultimate", "highrpm"]},

    # ── GT Auto ─────────────────────────────────────────────────────────
    {"id": "widebody", "name_fr": "Kit carrosserie large", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 150000, "price_max": 500000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["aero", "tires", "width"],
     "note": "Élargit les voies. Avec de nouvelles jantes, les pneus asphalte s'élargissent (pas les Dirt)."},
    {"id": "engine_swap", "name_fr": "Échange moteur (swap)", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 0, "price_max": 0, "permanent": False,
     "requires": [], "replaces": [], "tags": ["swap"], "level_override": 50,
     "note": "Rang collectionneur 50. Change puissance, poids, réservoir. Liste selon la voiture."},
    {"id": "wheels", "name_fr": "Jantes (+ largeur / +1 taille)", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 15000, "price_max": 80000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["tires", "width"],
     "note": "Après kit large : pneus plus larges. +1 taille = diamètre, grip et PP."},
    {"id": "aero_front", "name_fr": "Aéro avant (Type A/B)", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 50000, "price_max": 250000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["aero"],
     "note": "Déverrouille l'appui avant réglable 0–100."},
    {"id": "aero_side", "name_fr": "Jupes latérales", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 40000, "price_max": 180000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["aero"],
     "note": "Surtout visuel ; parfois lié à un pack aéro."},
    {"id": "aero_rear", "name_fr": "Aéro arrière (Type A/B)", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 50000, "price_max": 250000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["aero"],
     "note": "Appui arrière 0–100. Type diffuseur : 50–100 AV et AR + moins de traînée."},
    {"id": "aero_diffuser", "name_fr": "Diffuseur arrière", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 80000, "price_max": 300000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["aero"],
     "note": "Appui AV+AR 50–100, Cx en baisse. Certaines voitures : variante 'custom wing' 0/200."},
    {"id": "wing_ab", "name_fr": "Aileron Type A / Type B", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 60000, "price_max": 280000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["aero"],
     "note": "Appui arrière 50–150."},
    {"id": "wing_custom", "name_fr": "Aileron custom", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 80000, "price_max": 350000, "permanent": False,
     "requires": [], "replaces": ["wing_ab"], "tags": ["aero"],
     "note": "Appui arrière 50–200. Meilleur levier aéro."},
    {"id": "wingless", "name_fr": "Sans aileron (wingless)", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 0, "price_max": 0, "permanent": False,
     "requires": [], "replaces": [], "tags": ["aero"],
     "note": "0 appui d'aileron. Vmax / drag sur les énormes lignes droites."},
    {"id": "rollcage", "name_fr": "Arceau", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 80000, "price_max": 250000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["chassis"],
     "note": "Surtout visuel / RP. Pas un vrai palier de perf."},
    {"id": "tire_sticker", "name_fr": "Stickers de pneus", "shop": "gtauto", "tier": "gtauto",
     "group": "gtauto", "price_min": 5000, "price_max": 15000, "permanent": False,
     "requires": [], "replaces": [], "tags": ["cosmetic"]},
]

PARTS_BY_ID = {p["id"]: p for p in PARTS}

CATEGORIES = [
    {"id": "Road", "label": "Voiture de série (Road)"},
    {"id": "Gr.4", "label": "Gr.4 (GT4 / tourisme léger)"},
    {"id": "Gr.3", "label": "Gr.3 (GT3 / GTE)"},
    {"id": "Gr.2", "label": "Gr.2 (GT500 / DTM / GT1)"},
    {"id": "Gr.1", "label": "Gr.1 (prototypes / LMP / Hypercar)"},
    {"id": "Gr.B", "label": "Gr.B (rallye)"},
    {"id": "Super Formula", "label": "Super Formula"},
    {"id": "Kart", "label": "Kart"},
    {"id": "N100", "label": "N100 (≤ 149 ch)"},
    {"id": "N200", "label": "N200 (150–249 ch)"},
    {"id": "N300", "label": "N300 (250–349 ch)"},
    {"id": "N400", "label": "N400 (350–449 ch)"},
    {"id": "N500", "label": "N500 (450–549 ch)"},
    {"id": "N600", "label": "N600 (550–649 ch)"},
    {"id": "N700", "label": "N700 (650–749 ch)"},
    {"id": "N800", "label": "N800 (750–849 ch)"},
    {"id": "N1000", "label": "N1000 (950+ ch)"},
]

CAR_TYPES = [
    {"id": "Road Car", "label": "Road Car"},
    {"id": "Racing Car", "label": "Racing Car"},
    {"id": "Professionally-Tuned", "label": "Complete car / préparateur"},
    {"id": "Hypercar", "label": "Hypercar"},
    {"id": "Vision Gran Turismo", "label": "Vision Gran Turismo"},
]

DRIVETRAINS = [
    {"id": "FF", "label": "FF — traction"},
    {"id": "FR", "label": "FR — propulsion avant"},
    {"id": "MR", "label": "MR — centrale arrière"},
    {"id": "RR", "label": "RR — arrière / arrière-arrière"},
    {"id": "4WD", "label": "4WD — intégrale"},
]

WEATHER = [
    {"id": "dry", "label": "Sec"},
    {"id": "damp", "label": "Humide / intermédiaire"},
    {"id": "wet", "label": "Pluie"},
    {"id": "variable", "label": "Changeant"},
]


def part_unlocked(part, collector_level, has_ultimate=False):
    if part.get("shop") == "roulette":
        return bool(has_ultimate)
    lvl = part.get("level_override", TIERS[part["tier"]]["level"])
    return collector_level >= lvl


def get_part(pid):
    return deepcopy(PARTS_BY_ID[pid])
